names_list <- read.table("names_riodinidae.txt", sep = "_") %>% 
  rename(complete_name = V1) %>% 
  mutate(complete_name =as.character(complete_name)) %>% 
    rowwise %>% 
  mutate(family = NA,
         subfamily = NA,
         tribe = NA,
         genus = BBmisc::explode(complete_name, sep = " ")[1])
for(i in 1:nrow(names_list)){
  names_list$tribe[i] <- switch(names_list$genus[i],
                                Euselasia = "Euselasiini" ,
                                Methone = "Euselasiini",
                                Alesa = "Eurybiini",
                                Eurybia = "Eurybiini",
                                Anteros = "Helicopini",
                                Helicopis = "Helicopini",
                                Ourocnemis = "Helicopini",
                                Sarota = "Helicopini",
                                Argyrogrammana = "Incertae\ sedis",
                                Callistium = "Incertae\ sedis",
                                Calydna = "Incertae\ sedis",
                                Comphotis = "Incertae\ sedis",
                                Echenais = "Incertae\ sedis",
                                Emesis = "Incertae\ sedis",
                                Pachytone = "Incertae\ sedis",
                                Pachythone = "Incertae\ sedis",
                                Roeberella = "Incertae\ sedis",
                                Cremna = "Mesosemiini",
                                Hyphilaria = "Mesosemiini",
                                Ithomiola = "Mesosemiini",
                                Napaea = "Mesosemiini",
                                Eunogyra = "Mesosemiini",
                                Leucochimona = "Mesosemiini",
                                Mesophthalma = "Mesosemiini",
                                Mesosemia = "Mesosemiini",
                                Perophthalma = "Mesosemiini",
                                Semomesia = "Mesosemiini",
                                Aricoris = "Nymphidiini",
                                Adelotypa = "Nymphidiini",
                                Calospila = "Nymphidiini",
                                Dysmathia = "Nymphidiini",
                                Livendula = "Nymphidiini",
                                Menander = "Nymphidiini",
                                Nymphidium = "Nymphidiini",
                                Pandemos = "Nymphidiini",
                                Periplacis = "Nymphidiini",
                                Rodinia = "Nymphidiini",
                                Setabis = "Nymphidiini",
                                Zelotaea = "Nymphidiini",
                                Juditha = "Nymphidiini",
                                Lemonias = "Nymphidiini",
                                Synargis = "Nymphidiini",
                                Thisbe = "Nymphidiini",
                                Archaeonympha = "Nymphidiini",
                                Theope = "Nymphidiini",
                                Amarynthis = "Riodinini",
                                Ancyluris = "Riodinini",
                                Baeotis = "Riodinini",
                                Caria = "Riodinini",
                                Cariomothis = "Riodinini",
                                Chalodeta = "Riodinini",
                                Chamaelimnas = "Riodinini",
                                Charis = "Riodinini",
                                Chorinea = "Riodinini",
                                Colaciticus = "Riodinini",
                                Cyrenia = "Riodinini",
                                Dachetola = "Riodinini",
                                Detritivora = "Riodinini",
                                Isapis = "Riodinini",
                                Ithomeis = "Riodinini",
                                Lasaia = "Riodinini",
                                Lyropteryx = "Riodinini",
                                Melanis = "Riodinini",
                                Metacharis = "Riodinini",
                                Monethe = "Riodinini",
                                Notheme = "Riodinini",
                                Panara = "Riodinini",
                                Parcella = "Riodinini",
                                Pheles = "Riodinini",
                                Rhetus = "Riodinini",
                                Riodina = "Riodinini",
                                Syrmatia = "Riodinini",
                                Themone = "Riodinini",
                                Stalachtis = "Stalachtini",
                                Chimastrum = "Symmachiini",
                                Esthemopsis = "Symmachiini",
                                Mesene = "Symmachiini",
                                Panaropsis = "Symmachiini",
                                Phaenochitonia = "Symmachiini",
                                Pirascca = "Symmachiini",
                                Symmachia = "Symmachiini",
                                Xenandra = "Symmachiini"
                                )
}

for(i in 1:nrow(names_list)){
  names_list$subfamily[i] <- switch(names_list$tribe,
                                    Euselasiini = "Euselasinae",
                                    Eurybiini = "Riodininae",
                                    Helicopini = "Riodininae",
                                    "Incertae\ sedis" = "Incertae\ sedis",
                                    Mesosemiini = "Riodininae",
                                    Nymphidiini = "Riodininae",
                                    Riodinini  = "Riodininae",
                                    Stalachtini = "Riodininae",
                                    Symmachiini = "Riodininae"
                                    )
  
}
